### ISSUE TITLE
cpu count show wrong on MacBook pro intel chip

### ISSUE THREAD

**Issue by Ross249** [SunilWang/node-os-utils#32]
my macbook pro have 8 core , but osu.cpu.count() show 16 not 8.

**Comment by ulri-me** [comment]
@Ross249 This may or may not be a real issue.

If your MacBook Pro uses an Intel CPU, then this CPU supports hyper-threading, a technology and trademark developed/registered by Intel.

What is this?! :
An operating system is running tens to hundreds of tasks "simultaneously". In reality those tasks are handled one after another, and each task processing requires copying the task's data from RAM to the CPU's embedded cache memory, on which the CPU can perform calculations. Then the calculation results are copied back to the RAM of your computer.

The actual calculation is blazing fast while copying data from and to the RAM is quite slow in comparison. Therefore hyper-threading presents your OS two seperate CPU cores which each core being associated with a certain embedded cache section of the single physically existing CPU core.
Imagine your OS has to handle three tasks.
Your OS copies the data of task 1 from RAM to the embedded cache of virtual CPU core 1.
As soon as this task data is copied the CPU core starts the necessary calculations. While this happens, the OS is already copying data of task 2 to the embedded cache of virtual CPU core 2.
As soon as the CPU finished calculations, it can instantly continue with the calculations for task 2. In the meanwhile the OS copies the resulted data of task 1 back to RAM and copies the data of task 3 to the embedded cache of virtual CPU core 1.
Now the calculations of task 2 ended and the CPU can instantly continue with the calculations for task 3 while the OS copies back the results of the calculations of task 2 back to RAM.

In essence, with this technology your CPU can always run under full load, while the OS can perform the (in comparison) slow copying of task data from and to RAM in the background.

Due to all this, your OS show's the duplicate physical OS cores count, as it is really thinking that it can copy the data of a task to this logical CPU's cache.

That's also the difference between physical CPU cores (8 cores in your case, so 8 real calculation units), and logical CPU cores (16 in your case, so 16 CPU cache sections for task data storage).

**Comment by ulri-me** [comment]
Guess this issue can be closed :-).
